name = "labtime"
license = ""
licenselink = ""
description = ""
homepage = "http://example.com/"
tags = []
features = []
min_version = "0.41"

[author]
  name = "Jaap de Vos"
  homepage = "www.proliferoustech.com"
