baseURL = "https://test.lab-time.it"
languageCode = "en-us"
title = "Lab Time Test"
theme = "labtime"
enableRobotsTXT = true
copyright = "Copyrighted by Jaap de Vos. All rights reserved."
#PygmentsCodeFences = true
#pygmentsStyle = "monokai"
#pygmentsOptions = "linenos=table"

[params]
  subtitle = "read about networking, virtualization, home labs and related things"

[blackfriday]
  hrefTargetBlank = true

[author]
  name = "Jaap de Vos"
