baseURL = "https://www.proliferoustech.com"
languageCode = "en-us"
title = "Proliferous Technology"
theme = "labtime"
enableRobotsTXT = true
copyright = "Copyrighted by Jaap de Vos. All rights reserved."

[params]
  subtitle = "read about networking, virtualization, home labs and related things"

[blackfriday]
  hrefTargetBlank = true

[author]
  name = "Jaap de Vos"
