baseURL = "https://www.proliferoustech.com"
languageCode = "en-us"
title = "Proliferous Technology"
theme = "labtime"
enableRobotsTXT = true
copyright = "Copyrighted by Jaap de Vos. All rights reserved."
googleAnalytics = "UA-166310575-1"

[params]
  subtitle = "read about technology, with a focus on networking and automation, and whatever else comes along"

[blackfriday]
  hrefTargetBlank = true

[author]
  name = "Jaap de Vos"
